### ISSUE TITLE
Installing LibreWeb puts the following Error...

### ISSUE THREAD

**Issue by ghost** [vladboscaneanu/LibreWeb#1]
Ein Scripting Framework Fehler trat während der Ausführung vom Python-Skript vnd.sun.star.script:LibreWeb-admin-1.0.3.oxt|LibreWeb|main.py$Settings?language=Python&location=share:uno_packages auf.

Meldung: <class 'KeyError'>: 'LibreWeb-admin-1.0.3.oxt'
  File "C:\Program Files\LibreOffice 5\program\pythonscript.py", line 993, in getScript
    self.provCtx.uriHelper.getStorageURI(scriptUri) );
  File "C:\Program Files\LibreOffice 5\program\pythonscript.py", line 381, in getStorageUrlFromPersistentUrl
    package = self.mapPackageName2Path[ packageName ]

**Comment by vladboscaneanu** [comment]
Hi.
For most of users, including Windows users, the working variant is **user** version,
so I suggest you to use this one.
Both versions have the same functionality, change only the installation place.
Greetings

**Comment by ghost** [comment]
Sorry, I didn’t mention, that I used both variants. Both making the error.

Before I just updated Libreoffice to the latest stable Version of :
Version: 5.3.3.2 (x64)
Build-ID: 3d9a8b4b4e538a85e0782bd6c2d430bafe583448
CPU-Threads: 4; BS-Version: Windows 6.19; UI-Render: Standard; Layout-Engine: neu;
Gebietsschema: de-DE (de_DE); Calc: Group

Win Version is Win10 with all current updates installed.

Thanks

Reinhard

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Vladimir<mailto:notifications@github.com>
Gesendet: Montag, 12. Juni 2017 08:38
An: vladboscaneanu/LibreWeb<mailto:LibreWeb@noreply.github.com>
Cc: acidrbx<mailto:bringr@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [vladboscaneanu/LibreWeb] Installing LibreWeb puts the following Error... (#1)


Hi.
For most of users, including Windows users, the working variant is user version,
so I suggest you to use this one.
Both versions have the same functionality, change only the installation place.
Greetings

**Comment by vladboscaneanu** [comment]
Hello.
Please uninstall LibreWeb.
Reboot computer.
Install the **user** version, non admin.
Installing with double-click on extension file, then choose install for curent user only.
Then open File explorer and find in your C:\\Users\YOUR_USER_NAME\ find a hidden folder, AppData.
So go ahead and find this complete path : 
**C:\Users\YOUR_USER_NAME\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\**   
There try to find a package , named LibreWeb-user.oxt
After, open a Calc file (because extension works only in Calc documents),
and try again to run extension.
I am waiting for your answer.

**Comment by ghost** [comment]
Hello Vladimir,

What did I do so far? Ext. Was uninstalled after bringing up Errors.
So I didn’t need to restart the pc
Then installed the user Version by double clicking the .oxt file.
It didn’t ask to install it for the current user only.
Opened file Explorer and found „C:\Users\Reinhard\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu23483de541.tmp_\LibreWeb-user-1.0.3.oxt“
Running Calc again and trying to start is giving Errors:

„Ein Scripting Framework Fehler trat während der Ausführung vom Python-Skript vnd.sun.star.script:LibreWeb-user-1.0.3.oxt|LibreWeb|main.py$Start_Service?language=Python&location=user:uno_packages auf.

Meldung: <class 'TypeError'>: 'NoneType' object is not subscriptable
  File "C:\Program Files\LibreOffice 5\program\pythonscript.py", line 998, in getScript
    mod = self.provCtx.getModuleByUrl( fileUri )
  File "C:\Program Files\LibreOffice 5\program\pythonscript.py", line 458, in getModuleByUrl
    exec(code, entry.module.__dict__)
  File "C:\Users\Reinhard\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu187923df8j2.tmp_\LibreWeb-user-1.0.3.oxt\LibreWeb\main.py", line 12, in <module>
    do_update(ctx, msg_box)
  File "C:\Users\Reinhard\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu187923df8j2.tmp_\LibreWeb-user-1.0.3.oxt\LibreWeb\pythonpath\tools.py", line 186, in do_update
    _verify_update(ctx, msg_box)
  File "C:\Users\Reinhard\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages\lu187923df8j2.tmp_\LibreWeb-user-1.0.3.oxt\LibreWeb\pythonpath\tools.py", line 166, in _verify_update
    if online_version[0] > cur_version:“

Thanx and Regards

Reinhard


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Vladimir<mailto:notifications@github.com>
Gesendet: Dienstag, 13. Juni 2017 13:59
An: vladboscaneanu/LibreWeb<mailto:LibreWeb@noreply.github.com>
Cc: acidrbx<mailto:bringr@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [vladboscaneanu/LibreWeb] Installing LibreWeb puts the following Error... (#1)


Hello.
Please uninstall LibreWeb.
Reboot computer.
Install the user version, non admin.
Installing with double-click on extension file, then choose install for curent user only.
Then open File explorer and find in your C:\Users\YOUR_USER_NAME\ find a hidden folder, AppData.
So go ahead and find this complete path :
*C:\Users\YOUR_USER_NAME\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages*
There try to find a package , named LibreWeb-user.oxt
After, open a Calc file (because extension works only in Calc documents),
and try again to run extension.
I am waiting for your answer.

**Comment by vladboscaneanu** [comment]
Very well, now you got the working extension.
The error you see is my mistake: every one then LibreWeb starts, it check for updates.
You got this error because LibreOffice has no access to internet,maybe your computer is not connected to internet or LibreOffice is blocked by firewall.
I have to make some changes,to catch this kind of error.
However ,without any access to web, the extension is useless.
You must allow internet connection to LibreOffice /LibreWeb.
Greetings

**Comment by vladboscaneanu** [comment]
Reinhard, try the new 1.0.4 version.
This version on missing internet connection will not show you the error above.
Ciao

**Comment by ghost** [comment]
Vladimir,

it’s always connected to the inet. Every other Network Service works fine.

Reinhard

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Vladimir<mailto:notifications@github.com>
Gesendet: Mittwoch, 14. Juni 2017 08:27
An: vladboscaneanu/LibreWeb<mailto:LibreWeb@noreply.github.com>
Cc: acidrbx<mailto:bringr@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [vladboscaneanu/LibreWeb] Installing LibreWeb puts the following Error... (#1)


Very well, now you got the working extension.
The error you see is my mistake: every one then LibreWeb starts, it check for updates.
You got this error because LibreOffice has no access to internet,maybe your computer is not connected to internet or LibreOffice is blocked by firewall.
I have to make some changes,to catch this kind of error.
However ,without any access to web, the extension is useless.
You must allow internet connection to LibreOffice /LibreWeb.
Greetings

**Comment by ghost** [comment]
I’ll try it anyway…

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Vladimir<mailto:notifications@github.com>
Gesendet: Mittwoch, 14. Juni 2017 10:19
An: vladboscaneanu/LibreWeb<mailto:LibreWeb@noreply.github.com>
Cc: acidrbx<mailto:bringr@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [vladboscaneanu/LibreWeb] Installing LibreWeb puts the following Error... (#1)


Reinhard, try the new 1.0.4 version.
This version on missing internet connection will not show you the error above.
Ciao

**Comment by vladboscaneanu** [comment]
Thank you for feedback, I hope this help you.

Inviato dal mio telefono Windows 10

Da: acidrbx
Inviato: mercoledì 14 giugno 2017 15:49
A: vladboscaneanu/LibreWeb
Cc: Vladimir; Comment
Oggetto: Re: [vladboscaneanu/LibreWeb] Installing LibreWeb puts the followingError... (#1)

I’ll try it anyway…

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Vladimir<mailto:notifications@github.com>
Gesendet: Mittwoch, 14. Juni 2017 10:19
An: vladboscaneanu/LibreWeb<mailto:LibreWeb@noreply.github.com>
Cc: acidrbx<mailto:bringr@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [vladboscaneanu/LibreWeb] Installing LibreWeb puts the following Error... (#1)


Reinhard, try the new 1.0.4 version.
This version on missing internet connection will not show you the error above.
Ciao

**Comment by sojusnik** [comment]
When installing either `LibreWeb-user-1.0.7.oxt` or `LibreWeb-admin-1.0.7.oxt`, I receive the following error message:

> Failed to register package for vnd.sun.star.expand:$UNO_USER_PACKAGES_CACHE/uno_packages/lu27661f2iyy2.tmp_/LibreWeb-user-1.0.7.oxt/LibreWeb/

Happens with LibreOffice Version: 6.0.4.2 on Ubuntu 17.10. My Internet is working fine.

Any ideas how to solve this?

**Comment by sojusnik** [comment]
I've done that, even made a [video](https://mega.nz/#!ylJXjIgC!j_uOQkfFZ-rkygGa7JWzcjFcrpIwOor2MmQwDnzlr98), but without success. Any other suggestions?

**Comment by vladboscaneanu** [comment]
There is a way to use the package, without install it. But this is a hard
way. For now check manually, if you have any folder named LibreWeb , in
your user folder, also looking for something in LibreOffice main
application. After open LibreOffice and check in Macro Libraries if you
have a Library, named LibreWeb. Did you install before LibreWeb and use it?
What OS do you have? Do you have administrator's rights on your computer?
Open LibreOffice extensions site and find MRI extension, which is also
written in python, install it and try it. Does it works? Why would you like
to use so much LibreWeb? Please answer to all questions. With respect ,
Vladimir.

Il lun 21 mag 2018, 00:02 sojusnik <notifications@github.com> ha scritto:

**Comment by sojusnik** [comment]
I've deleted all folders and files in `~/.config/libreoffice` connected to LibreWeb, but this didn't help either.

LibreWeb is also not present in the macros.

I've never installed LibreWeb before.

I'm on Ubuntu 17.10 with admin rights.

Installing the [MRI](https://extensions.libreoffice.org/extensions/mri-uno-object-inspection-tool) extension shows this:
> (com.sun.star.uno.RuntimeException) { { Message = "<class 'SyntaxError'>: invalid syntax (MRI.py, line 21), traceback follows\X000a  File \"/usr/lib/libreoffice/program/pythonloader.py\", line 149, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"/usr/lib/libreoffice/program/pythonloader.py\", line 102, in getModuleFromUrl\X000a    codeobject = compile( src, encfile(filename), \"exec\" )\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

Because of [this](https://www.reddit.com/r/libreoffice/comments/8kleil/how_to_fetch_data_from_a_website_using/) recommendation I want to give LibreWeb a try.

**Comment by vladboscaneanu** [comment]
Something goes strange on your case , your system rejects definitely all
python extensions..you have to fix it, a lot of beautiful extensions ,
written in python, is arriving.
---------------------------------------------------------------------------------------------------------------------
This the hard way to use LibreWeb.
Extract the folder LibreWeb from zip file.
Copy the folder to your app scripts.
In Windows this is *C:\Program Files\LibreOffice\share\Scripts\python *
After putting here the folder, open LibreOffice, try to find in LibreOffice
macros the LibreWeb library, then
run a macro, Start_Service (see Screenshot) ..let me know what you see.


2018-05-21 10:37 GMT+02:00 sojusnik <notifications@github.com>:

**Comment by sojusnik** [comment]
The manual installation didn't work either, but I finally found the solution: just install `libreoffice-script-provider-python` from Ubuntu's repository and you are good to go!

**Comment by vladboscaneanu** [comment]
As I said before, the problem is in your system. I hope you will enjoy
LibreWeb.

Il lun 21 mag 2018, 14:26 sojusnik <notifications@github.com> ha scritto:

**Comment by sojusnik** [comment]
While this is true for this issue, it seems not with [that one](https://github.com/vladboscaneanu/LibreWeb/issues/3) :)

**Comment by vladboscaneanu** [comment]
I have no chance to try it on Ubuntu, I am really sorry... Maybe in the
future I will have a computer, running Ubuntu, so I will check the code. As
I know some services in Ubuntu are OS-specifically, so there's needing to
test intensively. Good day, thanks for trying.

Il lun 21 mag 2018, 14:43 sojusnik <notifications@github.com> ha scritto:

**Comment by sojusnik** [comment]
If you feel like it, then you could try to run [Ubuntu](https://www.ubuntu.com/download/desktop) in a virtual system, f.i. with [Virtualbox](https://www.virtualbox.org/).

**Comment by vladboscaneanu** [comment]
My computer is very slow, it is an old model with 2 gb Ram and 5 Gb free
disk space...I am afraid that Virtual Box may kills him definitely.. Bye.

Il lun 21 mag 2018, 16:38 sojusnik <notifications@github.com> ha scritto:

**Comment by vladboscaneanu** [comment]
I will try to making some changes soon, to fix Ubuntu's problem. Would you
like to participate, by testing code on your machine? If yes, please send
your email address, to continue privately. If no, sorry for disturbing.

Il lun 21 mag 2018, 17:00 vladimir boscaneanu <vladboscaneanu@gmail.com> ha
scritto:

**Comment by sojusnik** [comment]
I'm sorry, but I won't have time for that.
